export interface ITimeRange {
	/** Start time of the range in milliseconds since epoch */
	start: number
	/** End time of the range in milliseconds since epoch */
	end: number
}

// Session types
export interface SessionType {
	_id: string // Used for deletion, determining current session and key in list
	docExpires: string // Used to determine when the session document expires (ISO string)
	sessionExpires: string | null // Used to determine when session is expired if stayLoggedIn is true (Uses rolling expiration) (ISO string)
	stayLoggedIn: boolean // Used to determine if session is persistent
	type: 'admin' | 'kiosk' | 'unknown' // Used to infer user information
	userId: UserType['_id'] | null // Used to determine which user this session belongs to
	ipAddress: string // Ip address of the user
	loginTime: string // Time of login (ISO string)
	lastActivity: string // Time of last activity (ISO string)
	userAgent: string // Agent information
}

// Event types
export interface EventType {
	/**
	 * ID of the event
	 * - This is a unique identifier for the event, used to reference it in the database.
	 * - It is a string that is generated by the database.
	 */
	_id: string

	/**
	 * Name of the event
	 * - This is a short, descriptive name for the event.
	 * - Maximum length is 50 characters.
	 */
	name: string

	/**
	 * Description of the event
	 * - This is a longer, more detailed description of the event.
	 * - Maximum length is 1000 characters.
	 * - This can be left undefined/null if no description is provided.
	 */
	description?: string

	/**
	 * Members of the event
	 * - Each member has a userId, role, and availability status.
	 * - `userId`: ID of the user.
	 * - `role`: Role of the user in the event, can be 'creator', 'admin', or 'participant'.
	 * - `availabilityStatus`: Status of the user's availability for the event, can be 'available', 'unavailable', or 'invited'. This can only be set by the member themselves, but read by all members.
	 */
	members: {
		/** User ID of the member */
		userId: string
		/** Role of the member in the event
		 * - `creator` The user who created the event.
		 * - `admin` A user with administrative privileges for the event.
		 * - `participant` A regular participant in the event.
		 */
		role: 'creator' | 'admin' | 'participant'
		/** Availability status of the member for the event
		 * - `available` The member is available for the event.
		 * - `unavailable` The member is not available for the event.
		 * - `invited` The member has been invited to the event but has not yet responded.
		 * - This can only be set by the member themselves, but read by all members.
		 */
		availabilityStatus: 'available' | 'unavailable' | 'invited'
	}[]

	/**
	 * Scheduling method for the event
	 * - `fixed` Event has a fixed time and cannot be changed.
	 * - `flexible` Event will be scheduled at any time within the specified time window, subject to constraints.
	 */
	schedulingMethod: 'fixed' | 'flexible'

	/**
	 * Duration of the event in ms
	 * - This is used to determine how long the event will last.
	 * - If the schedulingMethod is 'flexible', this will be used to determine available times for the event.
	 * - If the schedulingMethod is 'fixed', this will be used to determine the end time of the event. It should be calculated as the difference between the start time and a "virtual" end time UI element of the event.
	 */
	duration: number

	/**
	 * Time window for the event
	 * - `timeWindow.start` Start time of the time window in milliseconds since epoch.
	 * - `timeWindow.end` End time of the time window in milliseconds since epoch.
	 * - This is used to determine when the event can occur for flexible scheduling.
	 * - If the schedulingMethod is 'fixed', this will be ignored.
	 */
	timeWindow?: ITimeRange

	/** Lifecycle status of the event
	 * - `scheduling` Event is being scheduled. It may or may not have a tentative scheduled time.
	 * - `confirmed` Event has been confirmed with a scheduled time. The scheduled time is set and cannot be changed.
	 * - `cancelled` Event has been cancelled and will not occur, despite having a scheduled time.
	*/
	status: 'scheduling' | 'confirmed' | 'cancelled'

	/**
	 * The current scheduled time for the event, if any.
	 * - This can only be set when the schedulingMethod is 'fixed'.
	 * - If the schedulingMethod is 'flexible', this will automatically be determined based on the preferred times and constraints.
	 * - If the event is in 'scheduling' status, this may be null.
	 * - If the event is in 'confirmed' status, this will be a valid timestamp.
	 */
	scheduledTime?: number

	/**
	 * Visibility of the event
	 * - `draft` Event is in draft state, not visible to any users except for creators and admins.
	 * - `public` Event is visible to all users.
	 * - `private` Event is visible only to the members of the event.
	 * - This can be used to control who can see and interact with the event.
	 */
	visibility: 'draft' | 'public' | 'private'

	/**
	 * Blackout periods for the event
	 * - `blackoutPeriods.start` Start time of the blackout period in milliseconds since epoch.
	 * - `blackoutPeriods.end` End time of the blackout period in milliseconds since epoch.
	 * - This is used to prevent scheduling the event during these times.
	 * - If the schedulingMethod is 'flexible', this will be used to determine available times for the event.
	 * - If the schedulingMethod is 'fixed', this will be ignored.
	*/
	blackoutPeriods?: ITimeRange[]

	/**
	 * Preferred times for the event
	 * - `preferredTimes.start` Start time of the preferred time range in milliseconds since epoch.
	 * - `preferredTimes.end` End time of the preferred time range in milliseconds since epoch.
	 * - This is used to suggest times for the event, but does not guarantee that the event will be scheduled at these times.
	 * - If the schedulingMethod is 'flexible', this will be used to determine the best time for the event.
	 * - If the schedulingMethod is 'fixed', this will be ignored.
	*/
	preferredTimes?: ITimeRange[]

	/**
	 * Intra-day start constraint for the event, in ms of the day
	 * - `dailyStartConstraints.start` Start time of the constraint in milliseconds since epoch.
	 * - `dailyStartConstraints.end` End time of the constraint in milliseconds since epoch.
	 * - This is used to prevent scheduling the event outside of these times. This only applies to the start time of the event.
	 * - If the schedulingMethod is 'flexible', this will be used to determine available times for the event.
	 * - If the schedulingMethod is 'fixed', this will be ignored.
	 */
	dailyStartConstraints?: ITimeRange[]

	/** Created at timestamp */
	createdAt: string
	/** Updated at timestamp */
	updatedAt: string
}

// Event creation payload allowed from client
export interface EventPostType {
	name: string
	description?: string
	members: Array<{
		userId: string
		role: 'creator' | 'admin' | 'participant'
	}>,
	timeWindow?: ITimeRange
	duration: number
	schedulingMethod: 'fixed' | 'flexible'
	scheduledTime?: number
	visibility: 'draft' | 'public' | 'private'
	blackoutPeriods?: ITimeRange[]
	preferredTimes?: ITimeRange[]
	dailyStartConstraints?: ITimeRange[]
}

// User types
export interface UserType {
	/** ID of the user */
	_id: string
	/** Username of the user */
	username: string
	/** Email of the user, null if not the current user */
	email: string | null
	/** If the user is not confirmed, the expiration date will be set */
	expirationDate: string | null
	/** If the user has confirmed their email, null if not the current user */
	confirmed: boolean | null
	/** Created at timestamp */
	createdAt: string
	/** Updated at timestamp */
	updatedAt: string
}
